### ISSUE TITLE
讨论：配置文件优化

### ISSUE THREAD

**Issue by suxb201** [aliyun/redis-shake#756]
当前版本配置文件：
```toml
function = ""


[sync_reader]
# ...


[redis_writer]
# ...

[advanced]
# ...

[module]
# ...
```

计划改动为：
```toml
[sync_reader]
# ...


[redis_writer]
# ...

[filter]
allow_key_prefix = "myapp"
allow_key_suffix = "myapp"
block_key_prefix = "myapp"
block_key_suffix = "myapp"

allow_db = []
block_db = []

allow_command = []
block_command = []

allow_command_group = []
block_command_group = []

function = ""

[advanced]
# ...
```

改动有：
1. 新增 `filter`，里面增加常用的过滤选项，基于 `lua` 的 `function` 过滤作为备用选项。好处有亮点：a. 多数场景下用户配置更方便，不需要去写 `lua` 脚本 b. `RedisShake` 过滤效率更高
2. `module` 放到 `advanced ` 中，低频配置应该更隐藏，避免给常用场景造成干扰。
3. 其余考虑的点：`target_redis_proto_max_bulk_len` 是否需要换个名字，从 issue 来看，这个配置使用频率比较高。

个人意见，欢迎大家提出别的看法。
