### ISSUE TITLE
阿里云使用scan_reader迁移到腾讯云报错

### ISSUE THREAD

**Issue by runfali** [aliyun/redis-shake#762]
### 问题描述（Issue Description）

阿里云使用scan迁移到腾讯云

Please provide a brief description of the issue you encountered.

### 环境信息（Environment）

- RedisShake 版本（RedisShake Version）：4.0.3
- Redis 源端版本（Redis Source Version）：5.0
- Redis 目的端版本（Redis Destination Version）：5.0
- Redis 部署方式（standalone/cluster/sentinel）：cluster
- 是否在云服务商实例上部署（Deployed on Cloud Provider）：是

### 日志信息（Logs）

![image](https://github.com/tair-opensource/RedisShake/assets/39327978/ff3ebdaf-b2b2-4a9b-926e-2653d728fe3c)

### 其他信息（Additional Information）

```toml
function = ""

[scan_reader]
cluster = true            # set to true if source is a redis cluster
address = "r-2zesey2piiemnzguel.redis.rds.aliyuncs.com:6379" # when cluster is true, set address to one of the cluster node
username = ""              # keep empty if not using ACL
password = ""              # keep empty if no authentication is required
ksn = false                # set to true to enabled Redis keyspace notifications (KSN) subscription
tls = false
dbs = []                   # set you want to scan dbs such as [1,5,7], if you don't want to scan all
prefer_replica = true      # set to true if you want to sync from replica node

[redis_writer]
cluster = true            # set to true if target is a redis cluster
address = "10.5.1.219:6379" # when cluster is true, set address to one of the cluster node
username = ""              # keep empty if not using ACL
password = ""              # keep empty if no authentication is required
tls = false
off_reply = false       # ture off the server reply

[advanced]
dir = "data"
ncpu = 0        # runtime.GOMAXPROCS, 0 means use runtime.NumCPU() cpu cores
pprof_port = 0  # pprof port, 0 means disable
status_port = 0 # status port, 0 means disable

log_file = "shake.log"
log_level = "debug"     # debug, info or warn
log_interval = 5       # in seconds

rdb_restore_command_behavior = "panic" # panic, rewrite or skip

pipeline_count_limit = 1024

target_redis_client_max_querybuf_len = 1024_000_000

target_redis_proto_max_bulk_len = 512_000_000

aws_psync = "" # example: aws_psync = "10.0.0.1:6379@nmfu2sl5osync,10.0.0.1:6379@xhma21xfkssync"

empty_db_before_sync = false

[module]
target_mbbloom_version = 20603
```
